import { CareerQuest } from './career-quest.model';

type SeedQuest = Omit<CareerQuest, 'status' | 'completedAt'>;

/** First-month plan (roadmap weeks 1–4) plus the three Boss Quests. Generic content. */
export const CAREER_SEED_QUESTS: SeedQuest[] = [
  // ---- Semana 1: Teste de Entrada + setup ----
  {
    id: 'q-w1-python-entry',
    type: 'quest',
    week: 1,
    title: 'Teste de Entrada — Python',
    skillIds: ['PY-02', 'PY-03'],
    level: 2,
    objective:
      'Medir o nível real de Python: média/mediana/moda, contar ocorrências num CSV, classe ContaBancaria com exception, comprehension e corrigir um script com 3 bugs.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'Arquivo único com as 5 soluções no career-quest-lab.',
    evidence: 'Registrar como TESTE no PY-02: 4/5 = passou (L2 provisório); menos = L1.',
    estimatedHours: 1.5,
    prerequisites: 'Nenhum. Não estudar antes.',
  },
  {
    id: 'q-w1-sql-entry',
    type: 'quest',
    week: 1,
    title: 'Teste de Entrada — SQL',
    skillIds: ['DB-01', 'DB-02'],
    level: 2,
    objective:
      'Instalar PostgreSQL local, carregar o dataset dvdrental e escrever 8 queries (filtros, JOINs, GROUP BY/HAVING, subquery, top-N, window function, query errada).',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'sql/entrada.sql com as 8 queries comentadas.',
    evidence: 'Registrar como TESTE no DB-02: 6/8 = passou.',
    estimatedHours: 1.5,
    prerequisites: 'Nenhum.',
  },
  {
    id: 'q-w1-git-linux-entry',
    type: 'micro',
    week: 1,
    title: 'Teste de Entrada — Git e Linux',
    skillIds: ['SE-01', 'LX-01'],
    level: 2,
    objective:
      'Git: branch, merge com conflito, desfazer commit, recuperar arquivo. Linux: achar arquivos por nome/conteúdo, pipes, permissões, env vars.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'git-linux/entrada.md com o que fez sozinho e o que precisou consultar.',
    evidence: 'Registrar como TESTE no SE-01 e no LX-01.',
    estimatedHours: 1,
    prerequisites: 'Nenhum.',
  },
  {
    id: 'q-w1-setup',
    type: 'micro',
    week: 1,
    title: 'Setup do career-quest-lab',
    skillIds: ['SE-01', 'PY-04'],
    level: 2,
    objective:
      'Criar o repositório career-quest-lab (python/, sql/, git-linux/, log/), VS Code com ruff + pytest, ambiente virtual e autocomplete de IA DESLIGADO nesses projetos.',
    difficulty: 1,
    aiPolicy: 'no-ai',
    deliverable: 'Repositório público com estrutura e README.',
    evidence: 'Link do repositório como ARTEFATO no SE-01.',
    estimatedHours: 1,
    prerequisites: 'Nenhum.',
  },
  {
    id: 'q-w1-python-review',
    type: 'quest',
    week: 1,
    title: 'Revisão de Python básico focada nas falhas',
    skillIds: ['PY-02'],
    level: 2,
    objective:
      'Estudar os pontos que falharam no Teste de Entrada e resolver 6–8 exercícios curtos.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'python/semana-01/ com os exercícios.',
    evidence:
      'Log da semana (log/semana-01.md) + áudio de 2 min em inglês sobre a semana.',
    estimatedHours: 3,
    prerequisites: 'Teste de Entrada — Python.',
  },
  // ---- Semana 2: Python sem muleta ----
  {
    id: 'q-w2-python-basics',
    type: 'quest',
    week: 2,
    title: 'Três mini-programas sem IA',
    skillIds: ['PY-02'],
    level: 2,
    objective:
      'Contador de palavras, deduplicador de CSV e validador de e-mails — só com documentação.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'python/semana-02/ com os 3 programas.',
    evidence: 'ARTEFATO no PY-02.',
    estimatedHours: 3,
    prerequisites: 'Setup do career-quest-lab.',
  },
  {
    id: 'q-w2-debugging',
    type: 'micro',
    week: 2,
    title: 'Exceptions e debugging na prática',
    skillIds: ['PY-05'],
    level: 2,
    objective:
      'Provocar erros de propósito, ler tracebacks e seguir a execução com breakpoints na IDE.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'Nota curta com 5 erros, causa e como achou cada um.',
    evidence: 'EXPLICAÇÃO no PY-05.',
    estimatedHours: 1,
    prerequisites: 'Nenhum.',
  },
  {
    id: 'q-w2-cli-start',
    type: 'project',
    week: 2,
    title: 'CLI de gastos — v0',
    skillIds: ['PY-02', 'SE-01'],
    level: 2,
    objective:
      'argparse, ler CSV, categorizar por regras num dict e imprimir resumo, com commits pequenos.',
    difficulty: 3,
    aiPolicy: 'no-ai',
    deliverable: 'Projeto expense-cli no GitHub.',
    evidence: 'ARTEFATO no PY-02; code review da IA só no domingo, aplicada à mão.',
    estimatedHours: 4,
    prerequisites: 'Três mini-programas sem IA.',
  },
  // ---- Semana 3 ----
  {
    id: 'q-w3-sql-groupby',
    type: 'quest',
    week: 3,
    title: 'SQL: GROUP BY, HAVING, subqueries e CTEs',
    skillIds: ['DB-02'],
    level: 2,
    objective: '6 problemas, cada um com comentário explicando a lógica.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'sql/semana-03.sql.',
    evidence: 'ARTEFATO no DB-02.',
    estimatedHours: 3,
    prerequisites: 'Teste de Entrada — SQL.',
  },
  {
    id: 'q-w3-bandit',
    type: 'micro',
    week: 3,
    title: 'OverTheWire Bandit — níveis 0 a 10',
    skillIds: ['LX-01', 'LX-02'],
    level: 2,
    objective: 'Praticar terminal, pipes, find/grep e permissões sem IA.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'git-linux/bandit.md com os comandos usados (sem as senhas).',
    evidence: 'ARTEFATO no LX-01.',
    estimatedHours: 1.5,
    prerequisites: 'Nenhum.',
  },
  {
    id: 'q-w3-git-branching',
    type: 'micro',
    week: 3,
    title: 'Learn Git Branching até rebase',
    skillIds: ['SE-01'],
    level: 3,
    objective: 'Completar os níveis até rebase e provocar conflitos de propósito no lab.',
    difficulty: 2,
    aiPolicy: 'no-ai',
    deliverable: 'Prints dos níveis + branch de exercício no lab.',
    evidence: 'ARTEFATO no SE-01.',
    estimatedHours: 1.5,
    prerequisites: 'Setup do career-quest-lab.',
  },
  {
    id: 'q-w3-cli-v1',
    type: 'project',
    week: 3,
    title: 'CLI de gastos — v1 com testes e README',
    skillIds: ['PY-02', 'SE-03', 'SE-06'],
    level: 2,
    objective:
      'Exportar JSON, tratar arquivo inválido com mensagem clara, 5 testes pytest e README de decisões.',
    difficulty: 3,
    aiPolicy: 'no-ai',
    deliverable: 'expense-cli v1 com testes passando.',
    evidence: 'ARTEFATO no PY-02 + EXPLICAÇÃO gravada de 3 min.',
    estimatedHours: 4,
    prerequisites: 'CLI de gastos — v0.',
  },
  // ---- Semana 4: provas do mês ----
  {
    id: 'q-w4-window',
    type: 'quest',
    week: 4,
    title: 'Window functions',
    skillIds: ['DB-03'],
    level: 2,
    objective: 'ROW_NUMBER, RANK, LAG e soma acumulada em 4 problemas.',
    difficulty: 3,
    aiPolicy: 'no-ai',
    deliverable: 'sql/semana-04-window.sql.',
    evidence: 'ARTEFATO no DB-03.',
    estimatedHours: 1.5,
    prerequisites: 'SQL: GROUP BY, HAVING, subqueries e CTEs.',
  },
  {
    id: 'q-w4-python-l2-exam',
    type: 'quest',
    week: 4,
    title: 'Prova — Python L2',
    skillIds: ['PY-02'],
    level: 2,
    objective:
      'Mini-projeto novo em 90 min, sem IA (ex.: ler log de acessos, agrupar por hora, exportar top 10).',
    difficulty: 3,
    aiPolicy: 'no-ai',
    deliverable: 'python/prova-l2/.',
    evidence: 'TESTE no PY-02 (passou/falhou).',
    estimatedHours: 1.5,
    prerequisites: 'CLI de gastos — v1.',
  },
  {
    id: 'q-w4-sql-l2-exam',
    type: 'quest',
    week: 4,
    title: 'Prova — SQL L2',
    skillIds: ['DB-02'],
    level: 2,
    objective: '10 queries em 60 min, sem IA; precisa acertar 8.',
    difficulty: 3,
    aiPolicy: 'no-ai',
    deliverable: 'sql/prova-l2.sql.',
    evidence: 'TESTE no DB-02 (passou/falhou).',
    estimatedHours: 1,
    prerequisites: 'Window functions.',
  },
  // ---- Boss Quests ----
  {
    id: 'boss-1-data-api',
    type: 'boss',
    title: 'Boss 1 — API de dados',
    skillIds: ['BE-03', 'DB-05', 'DK-04', 'SE-03', 'PY-06'],
    level: 3,
    objective:
      'API FastAPI que ingere e serve dados com PostgreSQL, migrations, autenticação, paginação, testes e Docker Compose (meses 4–6).',
    difficulty: 4,
    aiPolicy: 'ai-limited',
    deliverable:
      'Repositório com README de arquitetura, testes, CI e docker compose up funcionando.',
    evidence:
      'ADRs com trade-offs, cobertura de testes, vídeo de 10 min explicando (com trecho em inglês).',
    estimatedHours: 60,
    prerequisites: 'Python L3, SQL L3, Docker L2.',
  },
  {
    id: 'boss-2-pipeline',
    type: 'boss',
    title: 'Boss 2 — Pipeline idempotente na AWS',
    skillIds: ['DE-03', 'DE-04', 'DE-06', 'DE-07', 'CL-03', 'CL-09'],
    level: 3,
    objective:
      'Pipeline incremental e idempotente (API → S3 → transformação → modelo dbt) orquestrado no Airflow, com testes de dados, depois levado para AWS com Terraform (meses 7–12).',
    difficulty: 5,
    aiPolicy: 'ai-limited',
    deliverable:
      'Repositório + diagrama + infraestrutura como código + dashboard servido do modelo dimensional.',
    evidence:
      'Backfill demonstrado, alertas, estimativa de custo, decisões documentadas, apresentação de 15 min em inglês.',
    estimatedHours: 120,
    prerequisites: 'Boss 1 concluído, DE L2, Docker L3.',
  },
  {
    id: 'boss-3-data-ai-platform',
    type: 'boss',
    title: 'Boss 3 — Plataforma de dados + RAG em produção',
    skillIds: ['AI-05', 'AI-07', 'AI-08', 'SD-06', 'DE-08'],
    level: 4,
    objective:
      'Sobre os dados do Boss 2, um RAG do zero com pgvector, avaliação automatizada, observabilidade, controle de custo e proteção contra prompt injection (meses 13–18).',
    difficulty: 5,
    aiPolicy: 'ai-limited',
    deliverable: 'Sistema em produção com relatório de avaliação e design doc.',
    evidence:
      'Métricas antes/depois por estratégia, custo por consulta, incidentes simulados, artigo técnico publicado.',
    estimatedHours: 160,
    prerequisites: 'Boss 2 concluído, AI L3, AWS L3.',
  },
];
