/* eslint-disable max-len -- descriptive catalog content */
import { CareerCapstoneDef } from './career-quest.model';

/**
 * Capstone Projects: integrating projects that validate several skills at
 * once. CAP-01 and CAP-02 have NO AI / AI LIMITED parts; from CAP-03 on AI
 * may be used, but every technical decision must be explained and defended.
 */
export const CAREER_CAPSTONES: CareerCapstoneDef[] = [
  {
    id: 'CAP-01',
    title: 'Python Foundations Project',
    summary: 'Aplicação de linha de comando de tamanho médio, organizada e testada.',
    skillIds: ['PY-02', 'PY-03', 'PY-05', 'PY-06', 'SE-01', 'SE-02', 'SE-03'],
    prerequisites: ['PY-02 L2', 'SE-01 L2'],
    expectedLevel: 3,
    aiPolicy: 'no-ai',
    aiNote:
      'Implementação inicial NO AI. IA só depois, para code review, e você aplica à mão o que entender.',
    deliverables: [
      'CLI com 800–1.500 linhas em pacote src/ com módulos',
      'Testes com pytest (fixtures e parametrize)',
      'Typing com mypy passando e logging',
      'README com decisões técnicas',
    ],
    evidence: [
      'Link do repositório',
      'Gravação de 5 min explicando a arquitetura e as decisões',
      'Bug introduzido por outra pessoa, encontrado sem ajuda',
    ],
    checklist: [
      'Estrutura src/ com módulos separados por responsabilidade',
      'Configuração por variável de ambiente',
      'Tratamento de erros com mensagens claras',
      'Pelo menos 20 testes passando',
      'mypy sem erros',
      'Logging nos pontos importantes',
      'README: como rodar, decisões e trade-offs',
      'Histórico de commits pequenos e claros',
      'Explicação gravada',
    ],
    xp: 600,
    coins: 120,
  },
  {
    id: 'CAP-02',
    title: 'Backend Application',
    summary: 'API REST com FastAPI e PostgreSQL, autenticação, testes e migrations.',
    skillIds: [
      'PY-03',
      'NW-03',
      'BE-01',
      'BE-02',
      'BE-03',
      'BE-05',
      'DB-02',
      'DB-05',
      'SE-03',
      'SE-01',
    ],
    prerequisites: ['CAP-01', 'PY-03 L3', 'DB-02 L2'],
    expectedLevel: 3,
    aiPolicy: 'ai-limited',
    aiNote:
      'Modelagem do banco e rotas principais NO AI. IA permitida para revisão e testes extras, sempre explicando o que foi aceito.',
    deliverables: [
      'CRUD completo com paginação e tratamento de erros',
      'Autenticação JWT',
      'SQLAlchemy + migrations (Alembic)',
      'Testes de integração com banco',
    ],
    evidence: [
      'Repositório com README de arquitetura',
      'Diagrama do modelo de dados',
      'Coleção de requisições (ou OpenAPI) documentada',
    ],
    checklist: [
      'Modelagem relacional justificada (PK, FK, constraints)',
      'Endpoints REST consistentes (status codes, erros)',
      'Validação com Pydantic',
      'Autenticação e autorização',
      'Migrations versionadas',
      'Testes unitários e de integração',
      'README com decisões e trade-offs',
    ],
    xp: 900,
    coins: 180,
  },
  {
    id: 'CAP-03',
    title: 'Production Application',
    summary: 'Levar o CAP-02 para produção na AWS com segurança e observabilidade.',
    skillIds: [
      'DK-02',
      'DK-04',
      'SE-09',
      'CL-02',
      'CL-04',
      'PR-01',
      'PR-04',
      'PR-05',
      'PR-06',
      'OB-01',
      'OB-04',
      'SEC-01',
      'SEC-04',
    ],
    prerequisites: ['CAP-02', 'DK-04 L2', 'CL-02 L2'],
    expectedLevel: 3,
    aiPolicy: 'ai-allowed',
    aiNote:
      'IA pode ajudar, mas cada decisão (serviço AWS, estratégia de deploy, segredos) precisa estar explicada e defendida num ADR.',
    deliverables: [
      'Dockerfile multi-stage e docker compose para dev',
      'Pipeline de CI/CD (lint, testes, build, deploy)',
      'Deploy na AWS com config por ambiente e segredos gerenciados',
      'Logs estruturados, dashboard e um alerta',
    ],
    evidence: [
      'ADRs das decisões',
      'Print do dashboard e do alerta disparando',
      'Rollback demonstrado',
    ],
    checklist: [
      'Imagem pequena, usuário não-root',
      'CI rodando em cada PR',
      'Deploy automatizado',
      'Segredos fora do código',
      'Health checks',
      'Rollback testado',
      'Dashboard e alerta funcionando',
      'Estimativa de custo mensal',
    ],
    xp: 1100,
    coins: 220,
  },
  {
    id: 'CAP-04',
    title: 'Data Engineering Pipeline',
    summary:
      'Pipeline idempotente e incremental com warehouse, dbt, orquestração e qualidade.',
    skillIds: [
      'PY-03',
      'DB-03',
      'DB-07',
      'DE-02',
      'DE-03',
      'DE-04',
      'DE-05',
      'DE-06',
      'DE-07',
      'DE-10',
      'DE-12',
      'OB-05',
    ],
    prerequisites: ['CAP-02', 'DE-03 L2', 'DB-03 L2'],
    expectedLevel: 3,
    aiPolicy: 'ai-allowed',
    aiNote:
      'IA permitida; idempotência, particionamento, contratos e testes de dados precisam ser explicados e defendidos.',
    deliverables: [
      'Ingestão incremental para Parquet particionado',
      'Modelo dimensional em dbt (staging → marts) com testes',
      'Orquestração (Airflow) com retries e backfill',
      'Data contracts e checagens de qualidade/observabilidade',
    ],
    evidence: [
      'Backfill demonstrado sem duplicar dados',
      'Diagrama da arquitetura',
      'Relatório de qualidade de dados',
    ],
    checklist: [
      'Reprocessar não duplica dados (idempotência)',
      'Schema/data contract validado na entrada',
      'Particionamento e file layout justificados',
      'SCD tipo 2 em pelo menos uma dimensão',
      'Testes de dados no dbt',
      'Alerta de freshness/volume',
      'Lineage documentado',
    ],
    xp: 1200,
    coins: 240,
  },
  {
    id: 'CAP-05',
    title: 'AI Application',
    summary: 'Aplicação de RAG construída do zero, avaliada e em produção.',
    skillIds: [
      'AI-01',
      'AI-02',
      'AI-03',
      'AI-04',
      'AI-05',
      'AI-07',
      'AI-08',
      'BE-03',
      'OB-03',
      'PR-04',
      'MAS-08',
    ],
    prerequisites: ['CAP-03', 'AI-04 L2'],
    expectedLevel: 3,
    aiPolicy: 'ai-allowed',
    aiNote:
      'IA permitida, mas o pipeline de RAG é construído sem framework e cada escolha (chunking, retrieval, prompt) é defendida com números.',
    deliverables: [
      'Ingestão, chunking e embeddings em pgvector',
      'API com retrieval, citações e saída estruturada',
      'Conjunto de avaliação (≥ 30 perguntas) e métricas',
      'Deploy com tracing, custo e latência medidos',
    ],
    evidence: [
      'Relatório de avaliação comparando estratégias',
      'Custo por consulta',
      'Casos de falha analisados',
    ],
    checklist: [
      'Chunking comparado com números',
      'Retrieval com metadados',
      'Avaliação automatizada',
      'Proteção contra prompt injection',
      'Tracing e métricas de latência/custo',
      'Deploy funcionando',
    ],
    xp: 1300,
    coins: 260,
  },
  {
    id: 'CAP-06',
    title: 'Agentic Application',
    summary: 'Agente com tool calling, estado, memória, integrações (MCP) e guardrails.',
    skillIds: [
      'AI-06',
      'AI-09',
      'AG-01',
      'AG-03',
      'AG-04',
      'AG-05',
      'AG-08',
      'AG-09',
      'OB-03',
    ],
    prerequisites: ['CAP-05', 'AI-06 L2'],
    expectedLevel: 3,
    aiPolicy: 'ai-allowed',
    aiNote:
      'IA permitida; o agent loop é implementado por você antes de qualquer framework, e os guardrails são justificados.',
    deliverables: [
      'Agent loop com limite de passos e tratamento de erro',
      'Ferramentas via tool calling e uma integração MCP',
      'Memória de conversa e estado',
      'Avaliação e observabilidade (traces)',
    ],
    evidence: [
      'Traces de execuções reais',
      'Avaliação de tarefas completadas',
      'Análise de segurança (permissões, injection)',
    ],
    checklist: [
      'Loop implementado sem framework',
      'Tools validadas e com permissões mínimas',
      'Human-in-the-loop onde há risco',
      'Memória de curto e longo prazo',
      'Conjunto de avaliação',
      'Traces e custo por tarefa',
    ],
    xp: 1300,
    coins: 260,
  },
  {
    id: 'CAP-07',
    title: 'International Portfolio Project',
    summary:
      'Projeto final integrando backend, dados, IA, cloud, CI/CD, observabilidade, arquitetura e inglês técnico.',
    skillIds: [
      'SD-01',
      'SD-06',
      'SE-08',
      'DE-03',
      'AI-05',
      'CL-06',
      'OB-06',
      'EN-10',
      'EN-14',
      'EV-02',
      'EV-03',
    ],
    prerequisites: ['CAP-04', 'CAP-05'],
    expectedLevel: 4,
    aiPolicy: 'ai-allowed',
    aiNote:
      'IA permitida; o design doc, os trade-offs e a apresentação em inglês são seus e precisam resistir a perguntas.',
    deliverables: [
      'Design doc em inglês com requisitos, arquitetura e trade-offs',
      'Sistema em produção integrando dados e IA',
      'SLIs/SLOs definidos e monitorados',
      'Apresentação técnica de 15 min em inglês',
    ],
    evidence: [
      'Repositório e design doc públicos',
      'Gravação da apresentação',
      'Artigo técnico publicado',
    ],
    checklist: [
      'Design doc revisado por outra pessoa',
      'Arquitetura com diagramas',
      'SLOs e alertas',
      'Custos estimados e medidos',
      'Apresentação gravada em inglês',
      'Artigo técnico publicado',
    ],
    xp: 2000,
    coins: 400,
  },
];
