import {
  CareerAttribute,
  CareerHorizon,
  CareerSkillClass,
  CareerSkillDef,
} from './career-quest.model';

/**
 * Career Quest skill catalog. Generic (no personal data): what each skill is,
 * its class in the T-shaped profile, 12/24-month targets, prerequisites and
 * the observable criteria for each level. Personal levels/evidence live in the
 * RPG character state.
 */

const L = (...criteria: string[]): string[] => criteria;

// ---- level criteria per track (Level 1 .. Level 5) ----
const CRITERIA: Record<string, string[]> = {
  python: L(
    'Explica variáveis, tipos, condicionais, loops, funções e listas/dicts; lê um script de 30 linhas e diz o que faz.',
    'Sem código gerado por IA (doc permitida): funções e classes simples, ler/escrever CSV/JSON, try/except correto, comprehensions, lê traceback, 3 testes pytest. Prova: CLI pequeno em até 3h.',
    'Aplicação média (800–1.500 linhas) SEM IA: módulos organizados, typing (mypy ok), logging, config por env, testes com fixtures/mocks, README de decisões + explicação gravada de 5 min. Algoritmos fáceis/médios em 30 min.',
    'Escolhe com justificativa sync/async, threads/processos, dataclass/Pydantic; perfila e otimiza um gargalo real; código que outra pessoa mantém; faz code review útil.',
    'Define padrões de código do time, desenha bibliotecas internas, diagnostica concorrência/memória e ensina.',
  ),
  git: L(
    'Explica commit, branch e remote.',
    'Fluxo diário (branch, commit, push, PR) e resolve conflito simples.',
    'Explica merge × rebase; rebase interativo, cherry-pick, stash, recupera trabalho com reflog; commits atômicos. Teste: recuperar repositório quebrado sem IA.',
    'Define estratégia de branches/releases; usa bisect para achar o commit que introduziu um bug.',
    'Desenha o fluxo de um time (hooks, CI, convenções).',
  ),
  tests: L(
    'Explica para que servem testes unitários e de integração.',
    'Escreve testes unitários de funções puras com pytest.',
    'Fixtures, mocks, parametrize; testes de integração com banco em container; sabe o que NÃO testar.',
    'Define a estratégia de testes de um projeto (pirâmide, contratos, testes de dados); testes pegaram bugs reais.',
    'Define cultura e infraestrutura de testes de um time.',
  ),
  se: L(
    'Entende o conceito e por que ele importa.',
    'Aplica seguindo um exemplo ou guia.',
    'Aplica sozinho num projeto próprio e explica as decisões (README/ADR).',
    'Decide entre alternativas com trade-offs em problemas reais; revisa o trabalho de outras pessoas.',
    'Define padrões para um time e orienta outras pessoas.',
  ),
  sql: L(
    'Explica SELECT, WHERE e JOIN.',
    'JOINs, GROUP BY/HAVING, subquery e CTE. Teste: 10 exercícios fáceis/médios sem consulta, 80% de acerto.',
    'Window functions, dedupe, top-N por grupo, gaps & islands; explica a ordem lógica de execução. Teste: 8 problemas médios/difíceis de entrevista em ≤25 min cada.',
    'Lê EXPLAIN ANALYZE, propõe índices, reescreve queries lentas medindo antes/depois, modela tabelas para caso real.',
    'Estratégia de dados de um domínio (particionamento, tuning, OLTP × OLAP); diagnostica contenção/locks.',
  ),
  postgres: L(
    'Explica tabelas, chaves e tipos básicos.',
    'Cria tabelas com PK/FK/constraints a partir de um enunciado; usa psql.',
    'Modela um domínio em 3FN e justifica; transactions e isolamento; migrations; star schema com SCD2.',
    'Decide quando desnormalizar; índices compostos/parciais; particionamento; JSONB × colunas.',
    'Arquitetura de dados de um produto e capacity planning.',
  ),
  linux: L(
    'Navega no terminal e entende arquivos/diretórios.',
    'Pipes, grep/find, edita no terminal, entende chmod.',
    'Processos, SSH com chaves, env vars; diagnostica porta/serviço com curl, ss e logs; script bash. Teste: subir e depurar app numa VM sem IA.',
    'Configura servidor do zero com segurança básica; investiga CPU/memória/disco.',
    'Padroniza ambientes e diagnostica problemas complexos de SO e rede.',
  ),
  docker: L(
    'Explica imagem × container.',
    'Roda imagens, Dockerfile simples seguindo a doc, usa volumes.',
    'Dockerfile multi-stage do zero; Compose (app + Postgres + Redis) com healthchecks; depura container que não sobe. Teste: containerizar projeto desconhecido sem IA.',
    'Imagens pequenas e seguras (non-root), estratégia de config/segredos, decide Compose × ECS.',
    'Padrão de containerização do time e diagnósticos complexos.',
  ),
  api: L(
    'Explica request/response, métodos e status codes.',
    'Consome APIs com requests/httpx; cria endpoint FastAPI seguindo a doc.',
    'API CRUD completa SEM IA: Pydantic, SQLAlchemy, migrations, erros, paginação, JWT, testes e Docker; explica cada camada.',
    'Design consistente (versionamento, idempotência, rate limit), background jobs, observabilidade, performance medida.',
    'Arquitetura de serviços, contratos entre times, evolução sem quebrar clientes.',
  ),
  de: L(
    'Explica ETL × ELT, batch × streaming, warehouse/lakehouse, formatos colunares (Parquet) e o que é CDC.',
    'Pipeline simples com Pandas (API → transformar → Parquet/Postgres) seguindo referência; entende schema e particionamento por data.',
    'Pipeline idempotente e incremental SEM IA (retries seguros, reprocessar não duplica), schema/data contract validado, Parquet particionado com file layout pensado, testes de qualidade e logging; explica backfill e SCD tipo 2.',
    'Escolhe ferramentas com justificativa (Pandas × Spark × SQL); dados atrasados, evolução de schema, CDC, custo, particionamento, SLA e data observability (freshness, volume, schema, lineage).',
    'Desenha plataforma de dados (ingestão, lakehouse, contratos, governança, lineage ponta a ponta, observabilidade); lidera incidentes de dados.',
  ),
  orchestration: L(
    'Explica DAG, scheduling e modelagem em camadas.',
    'Roda um DAG/projeto dbt de exemplo e explica o que acontece.',
    'DAGs com dependências, retries e backfill; projeto dbt com staging/marts, testes, docs e incremental.',
    'Estrutura projeto grande, CI do dbt, sensores/SLAs, depura tarefas travadas.',
    'Define padrões de orquestração e modelagem para um time.',
  ),
  aws: L(
    'Explica regiões, IAM, S3, EC2, Lambda e o modelo de responsabilidade compartilhada.',
    'Cria S3, Lambda e RDS pelo console seguindo a doc; lê uma policy IAM.',
    'Policies de menor privilégio; deploy de pipeline (S3 → Lambda/Glue → Athena) via CLI/Terraform SEM IA; logs/alarmes; estima custo mensal.',
    'VPC/subnets/security groups justificados; escolha de serviços por custo e operação; infra 100% como código.',
    'Arquitetura multi-conta, segurança, FinOps, revisões de arquitetura.',
  ),
  ml: L(
    'Explica treino/teste, overfitting e métricas básicas.',
    'Treina modelos no scikit-learn seguindo notebook e interpreta métricas.',
    'Pipeline sklearn do zero SEM IA (preprocessing, CV, tuning); identifica vazamento; métrica certa para problema desbalanceado; explica bias/variance.',
    'Modelo em produção (API + versionamento + monitoramento de drift com MLflow); sabe quando NÃO usar ML.',
    'Define arquitetura de ML de um produto e orienta o time.',
  ),
  ai: L(
    'Explica tokens, contexto, embeddings e RAG.',
    'Chama API de LLM, saída estruturada, RAG seguindo tutorial.',
    'RAG do zero sem framework e sem IA gerando código (chunking, embeddings, pgvector, citações) + avaliação com ≥30 perguntas e métricas; explica onde ele erra.',
    'Compara chunking/retrieval com números; custo e latência; cache; proteção contra prompt injection; tool calling validado.',
    'Arquitetura de LLM em produção, avaliação contínua, segurança e liderança técnica.',
  ),
  sd: L(
    'Explica load balancer, cache, fila e réplica.',
    'Desenha sistemas clássicos seguindo um framework de entrevista.',
    'Desenha sozinho em 45 min (requisitos, estimativas, componentes, gargalos, trade-offs), incluindo data system design.',
    'Defende escolhas sob questionamento e adapta o desenho a mudanças de requisito.',
    'Conduz revisões de arquitetura e decisões de longo prazo.',
  ),
  bi: L(
    'Explica relatórios, medidas e modelo de dados.',
    'Monta relatórios seguindo um modelo pronto.',
    'Modelagem e DAX com autonomia; publica e mantém relatórios.',
    'Serve o BI a partir de um modelo dimensional bem feito (dbt), com performance e governança.',
    'Define a estratégia analítica de uma área.',
  ),
  english: L(
    'Entende textos e conversas lentas com apoio; responde frases curtas.',
    'Explica o próprio trabalho por 5 minutos com preparo.',
    'Conversa 20 minutos sobre um projeto e responde perguntas inesperadas.',
    'Faz uma entrevista técnica inteira em inglês com segurança.',
    'Conduz reuniões, discorda educadamente, defende decisões arquiteturais e apresenta sistemas complexos.',
  ),
  evidence: L(
    'Existe (perfil/repositório/rascunho), mas sem prova de competência.',
    'Um projeto ou texto com README/estrutura clara que outra pessoa entende.',
    'Projeto com testes, Docker, CI e decisões técnicas documentadas (trade-offs, problemas encontrados).',
    'Em produção/deploy com observabilidade, benchmarks e um artigo técnico explicando.',
    'Contribuições reconhecidas: open source aceito, palestra, liderança técnica visível.',
  ),
  dl: L(
    'Explica neurônio, camadas, função de ativação, loss e gradiente.',
    'Treina uma rede simples em PyTorch seguindo tutorial e interpreta as curvas de treino.',
    'Implementa SEM IA um loop de treino em PyTorch (dataset, dataloader, modelo, loss, otimizador, validação, early stopping) e diagnostica overfitting/underfitting.',
    'Escolhe arquitetura e estratégia (treinar do zero × fine-tuning × usar API) com custo e dados em mente; faz fine-tuning (ex.: LoRA) medindo o ganho.',
    'Desenha sistemas de DL em produção (serving, quantização, monitoramento) e orienta outras pessoas.',
  ),
  agents: L(
    'Explica o que é um agente (LLM + ferramentas + loop), memória e por que agentes falham.',
    'Monta um chatbot/agente seguindo tutorial ou framework e entende cada parte do código.',
    'Constrói SEM framework e SEM IA gerando código um agente com tool calling, memória de conversa, limite de passos e tratamento de erro; mede com um conjunto de avaliação.',
    'Decide quando usar agente × workflow fixo; observabilidade (traces), custo, guardrails, human-in-the-loop e segurança contra prompt injection em produção.',
    'Arquitetura de sistemas multi-agente em produção, avaliação contínua e liderança técnica no tema.',
  ),
  cs: L(
    'Explica o conceito com as próprias palavras.',
    'Explica com exemplos em Python e responde perguntas básicas sobre o tema.',
    'Aplica sozinho para analisar e decidir (complexidade do próprio código, estrutura certa, impacto em memória/CPU) e justifica.',
    'Diagnostica problemas reais de performance/memória medindo (profiling, benchmarks) antes de otimizar.',
    'Ensina o tema e toma decisões de arquitetura baseadas nele.',
  ),
  network: L(
    'Explica o conceito (o que acontece entre o cliente e o servidor).',
    'Observa na prática com ferramentas (curl, dig/nslookup, DevTools do navegador) seguindo um guia.',
    'Diagnostica sozinho problemas de conexão, DNS, HTTPS, portas ou CORS no próprio projeto.',
    'Configura proxies, TLS e balanceamento com justificativa e resolve incidentes de rede.',
    'Desenha a arquitetura de rede de um sistema e orienta o time.',
  ),
  security: L(
    'Explica o risco e por que o controle existe.',
    'Aplica um checklist (segredos fora do git, hash de senha com biblioteca, dependências atualizadas).',
    'Implementa os controles no próprio projeto SEM IA (segredos, validação de entrada, auth, menor privilégio) e explica as ameaças cobertas.',
    'Faz threat modeling, revisa código procurando vulnerabilidades e trata PII/compliance.',
    'Define práticas de segurança de um time e responde a incidentes.',
  ),
  observability: L(
    'Explica logs, métricas e traces e para que servem.',
    'Adiciona logs/métricas a um serviço seguindo um guia.',
    'Instrumenta o próprio serviço (logs estruturados, métricas, dashboard, alerta) e usa isso para achar um bug real.',
    'Define SLIs/SLOs e alertas sem ruído; investiga incidentes de produção pela telemetria.',
    'Define a estratégia de observabilidade de uma organização.',
  ),
  production: L(
    'Explica o conceito e o problema que ele resolve.',
    'Faz deploy seguindo um guia.',
    'Faz deploy do próprio app com config por ambiente, segredos, health checks e consegue fazer rollback — configuração escrita por você.',
    'Escolhe estratégia de deploy (blue-green, canary), zero-downtime e escala com justificativa; desenha o processo de release.',
    'Lidera engenharia de plataforma/release de um time.',
  ),
  mlsys: L(
    'Explica serving, batch × online, versionamento e drift.',
    'Serve um modelo seguindo tutorial.',
    'Constrói serving + versionamento + monitoramento para um modelo próprio e explica a escolha batch × online.',
    'Desenha sistemas de ML com trade-offs de custo, latência e qualidade; experimentação/A-B e resposta a drift.',
    'Arquitetura de plataforma de ML e liderança técnica.',
  ),
  interview: L(
    'Conhece o formato e o que é avaliado.',
    'Resolve problemas fáceis com tempo extra.',
    'Resolve problemas médios no tempo, explicando o raciocínio em voz alta.',
    'Passa em mock interviews completas (em inglês quando for o caso).',
    'Passa em entrevistas reais de nível sênior; sabe conduzir entrevistas.',
  ),
};

type Row = [
  id: string,
  name: string,
  group: string,
  track: string,
  skillClass: CareerSkillClass,
  target12: number,
  target24: number,
  startMonth: number,
  prerequisites?: string,
];

const TECHNICAL: Row[] = [
  ['PY-01', 'Lógica de programação', 'Programação', 'python', 'core', 3, 4, 1],
  ['PY-02', 'Python básico', 'Programação', 'python', 'core', 3, 4, 1, 'PY-01:1'],
  [
    'PY-03',
    'Python intermediário (OOP, módulos, exceptions)',
    'Programação',
    'python',
    'core',
    3,
    4,
    2,
    'PY-02:2',
  ],
  [
    'PY-04',
    'Ambientes e dependências',
    'Programação',
    'python',
    'important',
    3,
    3,
    2,
    'PY-02:2',
  ],
  ['PY-05', 'Debugging', 'Programação', 'python', 'core', 3, 4, 1, 'PY-02:1'],
  [
    'PY-06',
    'Typing (hints, mypy, Pydantic)',
    'Programação',
    'python',
    'core',
    3,
    4,
    3,
    'PY-03:2',
  ],
  [
    'PY-07',
    'Estruturas de dados e algoritmos',
    'Programação',
    'python',
    'important',
    2,
    3,
    2,
    'PY-02:2',
  ],
  [
    'PY-08',
    'Python avançado (decorators, protocolos)',
    'Programação',
    'python',
    'important',
    2,
    3,
    5,
    'PY-06:2',
  ],
  ['PY-09', 'Concorrência', 'Programação', 'python', 'important', 1, 3, 7, 'PY-06:2'],
  ['PY-10', 'Async', 'Programação', 'python', 'important', 2, 3, 6, 'PY-09:1'],
  ['PY-11', 'Boas práticas', 'Programação', 'python', 'core', 3, 4, 2, 'PY-02:2'],
  ['SE-01', 'Git', 'Software Engineering', 'git', 'core', 3, 4, 1],
  [
    'SE-02',
    'Organização de projetos',
    'Software Engineering',
    'se',
    'core',
    3,
    4,
    3,
    'PY-03:2',
  ],
  ['SE-03', 'Testes', 'Software Engineering', 'tests', 'core', 3, 4, 2, 'PY-03:2'],
  [
    'SE-04',
    'Logging e configuração',
    'Software Engineering',
    'se',
    'core',
    3,
    4,
    3,
    'PY-03:2',
  ],
  [
    'SE-05',
    'Clean Code e refatoração',
    'Software Engineering',
    'se',
    'important',
    3,
    4,
    4,
    'SE-03:2',
  ],
  [
    'SE-06',
    'Documentação (README, ADR)',
    'Software Engineering',
    'se',
    'important',
    3,
    4,
    3,
  ],
  [
    'SE-07',
    'Design patterns',
    'Software Engineering',
    'se',
    'supporting',
    2,
    3,
    7,
    'SE-03:3,PY-06:2',
  ],
  [
    'SE-08',
    'Arquitetura de software',
    'Software Engineering',
    'se',
    'important',
    2,
    3,
    9,
    'SE-03:3,PY-06:2',
  ],
  [
    'SE-09',
    'CI/CD',
    'Software Engineering',
    'se',
    'important',
    3,
    3,
    10,
    'SE-01:3,SE-03:2',
  ],
  ['BE-01', 'HTTP', 'Backend', 'api', 'important', 3, 4, 4],
  ['BE-02', 'REST e design de APIs', 'Backend', 'api', 'important', 3, 4, 4, 'BE-01:2'],
  ['BE-03', 'FastAPI', 'Backend', 'api', 'important', 3, 4, 5, 'BE-02:2,PY-03:3,PY-06:2'],
  [
    'BE-04',
    'Autenticação e autorização',
    'Backend',
    'api',
    'important',
    2,
    3,
    6,
    'BE-03:2',
  ],
  [
    'BE-05',
    'Banco na aplicação (SQLAlchemy, Alembic)',
    'Backend',
    'api',
    'important',
    3,
    3,
    5,
    'BE-03:2,DB-05:2',
  ],
  ['BE-06', 'Cache (Redis)', 'Backend', 'api', 'supporting', 2, 3, 8, 'BE-03:3,DK-04:2'],
  [
    'BE-07',
    'Filas e background jobs',
    'Backend',
    'api',
    'supporting',
    2,
    3,
    8,
    'BE-03:3,DK-04:2',
  ],
  ['DB-01', 'SQL básico', 'Database', 'sql', 'core', 4, 4, 1],
  [
    'DB-02',
    'SQL intermediário (JOIN, GROUP BY, CTE)',
    'Database',
    'sql',
    'core',
    3,
    4,
    1,
    'DB-01:2',
  ],
  [
    'DB-03',
    'SQL avançado (window functions)',
    'Database',
    'sql',
    'core',
    3,
    4,
    2,
    'DB-02:2',
  ],
  ['DB-04', 'Modelagem relacional', 'Database', 'postgres', 'core', 3, 4, 3, 'DB-02:2'],
  ['DB-05', 'PostgreSQL na prática', 'Database', 'postgres', 'core', 3, 4, 3, 'DB-04:2'],
  ['DB-06', 'Índices e otimização', 'Database', 'sql', 'core', 2, 4, 5, 'DB-03:2'],
  [
    'DB-07',
    'Modelagem analítica (star schema, SCD)',
    'Database',
    'postgres',
    'core',
    3,
    4,
    5,
    'DB-05:2',
  ],
  ['LX-01', 'Terminal e arquivos', 'Linux / Dev Tools', 'linux', 'important', 3, 3, 1],
  [
    'LX-02',
    'Processos, permissões e env vars',
    'Linux / Dev Tools',
    'linux',
    'important',
    3,
    3,
    2,
    'LX-01:2',
  ],
  [
    'LX-03',
    'SSH e servidores remotos',
    'Linux / Dev Tools',
    'linux',
    'important',
    3,
    3,
    3,
    'LX-02:2',
  ],
  [
    'LX-04',
    'Networking básico',
    'Linux / Dev Tools',
    'linux',
    'important',
    2,
    3,
    4,
    'LX-02:2',
  ],
  [
    'LX-05',
    'Shell scripting',
    'Linux / Dev Tools',
    'linux',
    'supporting',
    2,
    3,
    4,
    'LX-02:2',
  ],
  ['DK-01', 'Containers e images', 'Docker', 'docker', 'important', 3, 4, 4, 'LX-02:2'],
  ['DK-02', 'Dockerfile', 'Docker', 'docker', 'important', 3, 4, 4, 'DK-01:2'],
  ['DK-03', 'Volumes e networks', 'Docker', 'docker', 'important', 3, 3, 5, 'DK-02:2'],
  [
    'DK-04',
    'Docker Compose',
    'Docker',
    'docker',
    'important',
    3,
    4,
    5,
    'DK-03:2,DB-05:2',
  ],
  [
    'DK-05',
    'Debugging de containers',
    'Docker',
    'docker',
    'important',
    3,
    4,
    5,
    'DK-04:2',
  ],
  [
    'DE-01',
    'Pandas e transformação de dados',
    'Data Engineering',
    'de',
    'core',
    3,
    4,
    6,
    'PY-02:3',
  ],
  [
    'DE-02',
    'ETL × ELT, formatos e particionamento',
    'Data Engineering',
    'de',
    'core',
    3,
    4,
    7,
    'DB-02:2',
  ],
  [
    'DE-03',
    'Pipelines batch (idempotência, incremental)',
    'Data Engineering',
    'de',
    'core',
    3,
    4,
    7,
    'DE-01:2,SE-03:2',
  ],
  ['DE-04', 'Qualidade de dados', 'Data Engineering', 'de', 'core', 3, 4, 8, 'DE-03:2'],
  [
    'DE-05',
    'Data warehouse e lakehouse',
    'Data Engineering',
    'de',
    'core',
    2,
    4,
    8,
    'DB-07:2',
  ],
  [
    'DE-06',
    'dbt',
    'Data Engineering',
    'orchestration',
    'important',
    3,
    4,
    8,
    'DB-03:2,DB-07:2',
  ],
  [
    'DE-07',
    'Orquestração (Airflow)',
    'Data Engineering',
    'orchestration',
    'important',
    3,
    4,
    9,
    'DE-03:3,DK-04:2',
  ],
  [
    'DE-08',
    'Spark / PySpark',
    'Data Engineering',
    'de',
    'supporting',
    1,
    3,
    13,
    'DE-03:3,DB-03:3',
  ],
  [
    'DE-09',
    'Streaming (Kafka)',
    'Data Engineering',
    'de',
    'supporting',
    1,
    2,
    16,
    'DE-07:2,BE-07:2',
  ],
  ['CL-01', 'Fundamentos de cloud', 'Cloud (AWS)', 'aws', 'important', 3, 4, 7],
  ['CL-02', 'IAM', 'Cloud (AWS)', 'aws', 'important', 3, 4, 7, 'CL-01:2'],
  ['CL-03', 'Storage (S3)', 'Cloud (AWS)', 'aws', 'important', 3, 4, 7, 'CL-02:2'],
  [
    'CL-04',
    'Compute (Lambda, EC2, ECS)',
    'Cloud (AWS)',
    'aws',
    'important',
    3,
    4,
    8,
    'CL-02:2,PY-03:3',
  ],
  [
    'CL-05',
    'Bancos gerenciados (RDS)',
    'Cloud (AWS)',
    'aws',
    'important',
    2,
    3,
    9,
    'CL-02:2',
  ],
  [
    'CL-06',
    'Dados na AWS (Glue, Athena, Redshift)',
    'Cloud (AWS)',
    'aws',
    'important',
    2,
    4,
    10,
    'DE-02:2,CL-03:2',
  ],
  [
    'CL-07',
    'Networking (VPC, subnets, SG)',
    'Cloud (AWS)',
    'aws',
    'important',
    2,
    3,
    10,
    'CL-02:2,LX-04:2',
  ],
  [
    'CL-08',
    'Observabilidade (CloudWatch)',
    'Cloud (AWS)',
    'aws',
    'important',
    2,
    3,
    11,
    'CL-04:2',
  ],
  [
    'CL-09',
    'Infra como código (Terraform)',
    'Cloud (AWS)',
    'aws',
    'supporting',
    2,
    3,
    11,
    'CL-07:2',
  ],
  [
    'CL-10',
    'Azure (Blob, Functions, Synapse)',
    'Cloud (AWS)',
    'aws',
    'supporting',
    1,
    2,
    12,
    'CL-06:2',
  ],
  [
    'ML-01',
    'Estatística e probabilidade aplicadas',
    'Machine Learning',
    'ml',
    'supporting',
    2,
    3,
    13,
  ],
  ['ML-02', 'ML clássico', 'Machine Learning', 'ml', 'supporting', 2, 3, 14, 'ML-01:2'],
  [
    'ML-03',
    'Pré-processamento e features',
    'Machine Learning',
    'ml',
    'supporting',
    2,
    3,
    14,
    'ML-02:2',
  ],
  [
    'ML-04',
    'Avaliação e validação',
    'Machine Learning',
    'ml',
    'supporting',
    2,
    3,
    15,
    'ML-03:2',
  ],
  [
    'ML-05',
    'Deployment de modelo',
    'Machine Learning',
    'ml',
    'supporting',
    1,
    3,
    16,
    'ML-04:2,BE-03:2,DK-02:2',
  ],
  [
    'ML-06',
    'MLOps (MLflow, monitoring)',
    'Machine Learning',
    'ml',
    'supporting',
    0,
    2,
    19,
    'ML-05:2,CL-04:2',
  ],
  [
    'AI-01',
    'APIs de LLM (tokens, contexto, custo)',
    'IA Generativa',
    'ai',
    'important',
    3,
    4,
    10,
    'BE-01:2,PY-03:2',
  ],
  [
    'AI-02',
    'Prompting e structured outputs',
    'IA Generativa',
    'ai',
    'important',
    3,
    4,
    10,
    'AI-01:2',
  ],
  [
    'AI-03',
    'Embeddings e busca vetorial',
    'IA Generativa',
    'ai',
    'important',
    3,
    4,
    11,
    'AI-02:2,DB-05:2',
  ],
  [
    'AI-04',
    'Retrieval e chunking',
    'IA Generativa',
    'ai',
    'important',
    3,
    4,
    11,
    'AI-03:2',
  ],
  ['AI-05', 'RAG completo', 'IA Generativa', 'ai', 'important', 3, 4, 12, 'AI-04:2'],
  ['AI-06', 'Tool calling', 'IA Generativa', 'ai', 'important', 2, 3, 14, 'AI-02:3'],
  ['AI-07', 'Avaliação de LLM', 'IA Generativa', 'ai', 'important', 2, 4, 13, 'AI-05:2'],
  [
    'AI-08',
    'LLM em produção (custo, latência, segurança)',
    'IA Generativa',
    'ai',
    'important',
    1,
    3,
    15,
    'AI-07:2,CL-08:2',
  ],
  [
    'AI-09',
    'Agentes (fundamentos)',
    'IA Generativa',
    'agents',
    'important',
    1,
    3,
    13,
    'AI-06:2,AI-07:2',
  ],
  // ---- Agentes e Chatbots ----
  [
    'AG-01',
    'Chatbots conversacionais (histórico, estado, streaming)',
    'Agentes e Chatbots',
    'agents',
    'important',
    2,
    4,
    11,
    'AI-02:2,BE-03:2',
  ],
  [
    'AG-02',
    'Design de conversação (fallback, handoff humano)',
    'Agentes e Chatbots',
    'agents',
    'supporting',
    1,
    3,
    13,
    'AG-01:2',
  ],
  [
    'AG-03',
    'Agent loop (ReAct, planejamento, limite de passos)',
    'Agentes e Chatbots',
    'agents',
    'important',
    1,
    3,
    14,
    'AI-09:2,AI-06:3',
  ],
  [
    'AG-04',
    'Memória de agentes (curto e longo prazo)',
    'Agentes e Chatbots',
    'agents',
    'important',
    1,
    3,
    14,
    'AG-01:2,AI-03:3',
  ],
  [
    'AG-05',
    'MCP e integrações com ferramentas',
    'Agentes e Chatbots',
    'agents',
    'important',
    1,
    3,
    15,
    'AI-06:3,BE-03:3',
  ],
  [
    'AG-06',
    'Frameworks de agentes (LangGraph, LlamaIndex, Agents SDK)',
    'Agentes e Chatbots',
    'agents',
    'supporting',
    1,
    3,
    16,
    'AG-03:2',
  ],
  [
    'AG-07',
    'Multi-agentes e orquestração',
    'Agentes e Chatbots',
    'agents',
    'supporting',
    0,
    2,
    18,
    'AG-03:3',
  ],
  [
    'AG-08',
    'Avaliação e observabilidade de agentes (traces)',
    'Agentes e Chatbots',
    'agents',
    'important',
    1,
    3,
    15,
    'AI-07:2,AG-03:2',
  ],
  [
    'AG-09',
    'Segurança de agentes (permissões, injection, guardrails)',
    'Agentes e Chatbots',
    'agents',
    'important',
    1,
    3,
    16,
    'AG-03:2,AI-08:2',
  ],
  [
    'AG-10',
    'Deploy de chatbot (API, canais web/WhatsApp/Slack)',
    'Agentes e Chatbots',
    'agents',
    'supporting',
    1,
    3,
    15,
    'AG-01:3,DK-04:3',
  ],
  // ---- Deep Learning ----
  [
    'DL-01',
    'Redes neurais (fundamentos, backprop)',
    'Deep Learning',
    'dl',
    'supporting',
    1,
    3,
    15,
    'ML-02:2,ML-01:2',
  ],
  ['DL-02', 'PyTorch', 'Deep Learning', 'dl', 'supporting', 1, 3, 16, 'DL-01:2,PY-03:3'],
  [
    'DL-03',
    'Treino e otimização (regularização, schedulers)',
    'Deep Learning',
    'dl',
    'supporting',
    0,
    3,
    16,
    'DL-02:2,ML-04:2',
  ],
  [
    'DL-04',
    'NLP e Transformers (attention, tokenização)',
    'Deep Learning',
    'dl',
    'supporting',
    1,
    3,
    17,
    'DL-02:2',
  ],
  [
    'DL-05',
    'Hugging Face (modelos, datasets, pipelines)',
    'Deep Learning',
    'dl',
    'supporting',
    1,
    3,
    17,
    'DL-04:1,PY-03:3',
  ],
  [
    'DL-06',
    'Fine-tuning (LoRA/PEFT) × RAG',
    'Deep Learning',
    'dl',
    'supporting',
    0,
    2,
    19,
    'DL-03:2,AI-05:3',
  ],
  [
    'DL-07',
    'Visão computacional (CNNs)',
    'Deep Learning',
    'dl',
    'awareness',
    0,
    2,
    20,
    'DL-03:2',
  ],
  [
    'SD-01',
    'Escalabilidade e load balancing',
    'System Design',
    'sd',
    'supporting',
    1,
    3,
    13,
    'BE-03:3,DB-06:2,DK-04:3',
  ],
  [
    'SD-02',
    'Caching e escolha de banco',
    'System Design',
    'sd',
    'supporting',
    1,
    3,
    13,
    'SD-01:1',
  ],
  [
    'SD-03',
    'Filas e arquitetura orientada a eventos',
    'System Design',
    'sd',
    'supporting',
    1,
    3,
    14,
    'SD-01:1',
  ],
  [
    'SD-04',
    'Consistência, disponibilidade, confiabilidade',
    'System Design',
    'sd',
    'supporting',
    1,
    3,
    15,
    'SD-01:2',
  ],
  [
    'SD-05',
    'Observabilidade de sistemas',
    'System Design',
    'sd',
    'supporting',
    1,
    3,
    15,
    'SD-01:1',
  ],
  [
    'SD-06',
    'Data system design',
    'System Design',
    'sd',
    'important',
    1,
    3,
    14,
    'DE-03:3,SD-01:1',
  ],
  [
    'SD-07',
    'Sistemas distribuídos (conceitos)',
    'System Design',
    'sd',
    'awareness',
    0,
    2,
    18,
    'SD-04:2',
  ],
  ['BI-01', 'Power BI', 'BI', 'bi', 'supporting', 3, 4, 1],
  [
    'BI-02',
    'Ponte BI ↔ engenharia',
    'BI',
    'bi',
    'supporting',
    2,
    4,
    9,
    'BI-01:3,DB-07:2',
  ],
  // ---- Computer Science fundamentals ----
  [
    'CS-01',
    'Memória, stack/heap, processos e threads',
    'Computer Science',
    'cs',
    'important',
    2,
    3,
    3,
    'PY-02:2',
  ],
  ['CS-02', 'Complexidade Big O', 'Computer Science', 'cs', 'core', 2, 3, 2, 'PY-02:2'],
  [
    'CS-03',
    'Estruturas fundamentais de dados',
    'Computer Science',
    'cs',
    'core',
    2,
    3,
    2,
    'PY-02:2',
  ],
  [
    'CS-04',
    'CPU-bound vs I/O-bound',
    'Computer Science',
    'cs',
    'important',
    2,
    3,
    6,
    'CS-01:1',
  ],
  [
    'CS-05',
    'Serialização e formatos (JSON, CSV, Parquet)',
    'Computer Science',
    'cs',
    'important',
    3,
    3,
    3,
    'PY-02:2',
  ],
  // ---- Networking / Web fundamentals ----
  ['NW-01', 'TCP/IP básico', 'Networking / Web', 'network', 'important', 2, 3, 4],
  ['NW-02', 'DNS', 'Networking / Web', 'network', 'important', 2, 3, 4, 'NW-01:1'],
  [
    'NW-03',
    'HTTP/HTTPS por baixo',
    'Networking / Web',
    'network',
    'important',
    2,
    3,
    4,
    'NW-01:1',
  ],
  [
    'NW-04',
    'Portas, sockets e conexões',
    'Networking / Web',
    'network',
    'important',
    2,
    3,
    5,
    'NW-01:2',
  ],
  [
    'NW-05',
    'Proxy / reverse proxy',
    'Networking / Web',
    'network',
    'supporting',
    1,
    3,
    8,
    'NW-03:2',
  ],
  ['NW-06', 'TLS/SSL', 'Networking / Web', 'network', 'supporting', 1, 3, 8, 'NW-03:2'],
  ['NW-07', 'CORS', 'Networking / Web', 'network', 'supporting', 2, 3, 6, 'BE-02:2'],
  // ---- Security ----
  [
    'SEC-01',
    'Secrets e credenciais',
    'Security',
    'security',
    'important',
    3,
    3,
    4,
    'PY-03:2',
  ],
  [
    'SEC-02',
    'Hashing, encryption e TLS',
    'Security',
    'security',
    'important',
    2,
    3,
    8,
    'NW-06:1',
  ],
  [
    'SEC-03',
    'OWASP fundamentals',
    'Security',
    'security',
    'important',
    1,
    3,
    8,
    'BE-02:2',
  ],
  [
    'SEC-04',
    'Segurança de APIs',
    'Security',
    'security',
    'important',
    2,
    3,
    7,
    'BE-04:2',
  ],
  [
    'SEC-05',
    'IAM / least privilege',
    'Security',
    'security',
    'important',
    2,
    3,
    8,
    'CL-02:2',
  ],
  [
    'SEC-06',
    'Segurança de dados / PII',
    'Security',
    'security',
    'important',
    1,
    3,
    9,
    'DB-04:2',
  ],
  [
    'SEC-07',
    'Supply chain / dependências',
    'Security',
    'security',
    'supporting',
    1,
    3,
    10,
    'PY-04:2',
  ],
  // ---- Observability ----
  [
    'OB-01',
    'Logging estruturado',
    'Observability',
    'observability',
    'important',
    3,
    3,
    3,
    'SE-04:2',
  ],
  [
    'OB-02',
    'Métricas',
    'Observability',
    'observability',
    'important',
    2,
    3,
    9,
    'OB-01:2',
  ],
  [
    'OB-03',
    'Tracing',
    'Observability',
    'observability',
    'important',
    1,
    3,
    11,
    'OB-02:2',
  ],
  [
    'OB-04',
    'Monitoring / dashboards',
    'Observability',
    'observability',
    'important',
    2,
    3,
    10,
    'OB-02:2',
  ],
  [
    'OB-05',
    'Alertas',
    'Observability',
    'observability',
    'important',
    2,
    3,
    10,
    'OB-04:2',
  ],
  [
    'OB-06',
    'SLI / SLO / SLA',
    'Observability',
    'observability',
    'supporting',
    1,
    3,
    13,
    'OB-05:2',
  ],
  [
    'OB-07',
    'Debugging em produção',
    'Observability',
    'observability',
    'important',
    1,
    3,
    12,
    'OB-01:3,PY-05:3',
  ],
  // ---- Production / Deployment engineering ----
  [
    'PR-01',
    'Configuração por ambiente',
    'Production / Deploy',
    'production',
    'important',
    3,
    3,
    4,
    'SE-04:2',
  ],
  [
    'PR-02',
    'Secrets management',
    'Production / Deploy',
    'production',
    'important',
    2,
    3,
    9,
    'SEC-01:2',
  ],
  [
    'PR-03',
    'Build e release',
    'Production / Deploy',
    'production',
    'important',
    2,
    3,
    9,
    'SE-09:2,DK-02:2',
  ],
  [
    'PR-04',
    'Deploy',
    'Production / Deploy',
    'production',
    'important',
    2,
    3,
    9,
    'DK-04:2',
  ],
  [
    'PR-05',
    'Rollback',
    'Production / Deploy',
    'production',
    'important',
    1,
    3,
    10,
    'PR-04:2',
  ],
  [
    'PR-06',
    'Health checks',
    'Production / Deploy',
    'production',
    'important',
    2,
    3,
    6,
    'BE-03:2',
  ],
  [
    'PR-07',
    'Horizontal scaling',
    'Production / Deploy',
    'production',
    'supporting',
    1,
    3,
    13,
    'PR-04:2,SD-01:1',
  ],
  [
    'PR-08',
    'Deployment strategies (blue-green, canary)',
    'Production / Deploy',
    'production',
    'supporting',
    1,
    2,
    14,
    'PR-05:2',
  ],
  // ---- ML / AI Systems ----
  [
    'MAS-01',
    'Model serving',
    'ML / AI Systems',
    'mlsys',
    'important',
    1,
    3,
    14,
    'ML-05:1,BE-03:3',
  ],
  [
    'MAS-02',
    'Batch vs online inference',
    'ML / AI Systems',
    'mlsys',
    'important',
    1,
    3,
    14,
    'MAS-01:1',
  ],
  [
    'MAS-03',
    'Feature pipelines',
    'ML / AI Systems',
    'mlsys',
    'supporting',
    1,
    3,
    15,
    'DE-03:3,ML-03:2',
  ],
  [
    'MAS-04',
    'Model/version management',
    'ML / AI Systems',
    'mlsys',
    'important',
    1,
    3,
    15,
    'MAS-01:2',
  ],
  [
    'MAS-05',
    'Monitoring de modelo',
    'ML / AI Systems',
    'mlsys',
    'important',
    0,
    3,
    16,
    'MAS-04:2,OB-02:2',
  ],
  ['MAS-06', 'Drift', 'ML / AI Systems', 'mlsys', 'supporting', 0, 2, 17, 'MAS-05:1'],
  [
    'MAS-07',
    'Experimentação / A/B testing',
    'ML / AI Systems',
    'mlsys',
    'supporting',
    0,
    2,
    18,
    'ML-01:2',
  ],
  [
    'MAS-08',
    'Cost-performance trade-offs',
    'ML / AI Systems',
    'mlsys',
    'important',
    1,
    3,
    14,
    'AI-08:1',
  ],
  // ---- Data Engineering enrichment ----
  [
    'DE-10',
    'Data contracts e schemas',
    'Data Engineering',
    'de',
    'important',
    2,
    3,
    8,
    'DE-03:2',
  ],
  [
    'DE-11',
    'CDC (Change Data Capture)',
    'Data Engineering',
    'de',
    'supporting',
    0,
    2,
    15,
    'DE-03:3,DB-05:3',
  ],
  [
    'DE-12',
    'Data lineage e data observability',
    'Data Engineering',
    'de',
    'important',
    1,
    3,
    11,
    'DE-04:2',
  ],
  // ---- Containers at scale ----
  [
    'DK-06',
    'Kubernetes (conceitos)',
    'Docker',
    'docker',
    'awareness',
    0,
    1,
    20,
    'DK-04:3,PR-04:2',
  ],
];

const ENGLISH: Row[] = [
  ['EN-01', 'Listening', 'Compreensão', 'english', 'core', 3, 4, 1],
  ['EN-02', 'Speaking', 'Fala', 'english', 'core', 3, 4, 1],
  ['EN-03', 'Pronunciation', 'Fala', 'english', 'important', 3, 4, 1],
  ['EN-04', 'Vocabulary', 'Compreensão', 'english', 'core', 3, 4, 1],
  ['EN-05', 'Technical vocabulary', 'Técnico', 'english', 'core', 3, 4, 1],
  ['EN-06', 'Writing', 'Escrita', 'english', 'important', 3, 4, 2],
  ['EN-07', 'Technical writing', 'Escrita', 'english', 'important', 3, 4, 3, 'EN-06:2'],
  [
    'EN-08',
    'Small talk profissional',
    'Fala',
    'english',
    'important',
    3,
    4,
    2,
    'EN-02:2',
  ],
  ['EN-09', 'Explicar projetos', 'Técnico', 'english', 'core', 3, 4, 2, 'EN-02:2'],
  ['EN-10', 'Explicar arquitetura', 'Técnico', 'english', 'core', 2, 4, 6, 'EN-09:2'],
  ['EN-11', 'Fazer perguntas', 'Fala', 'english', 'important', 3, 4, 3, 'EN-02:2'],
  ['EN-12', 'Defender decisões', 'Técnico', 'english', 'important', 2, 4, 8, 'EN-10:2'],
  ['EN-13', 'Reuniões', 'Profissional', 'english', 'important', 3, 4, 6, 'EN-11:2'],
  ['EN-14', 'Apresentações', 'Profissional', 'english', 'important', 2, 4, 6, 'EN-09:2'],
  ['EN-15', 'Entrevistas', 'Profissional', 'english', 'core', 3, 4, 9, 'EN-09:3'],
  ['EN-16', 'Negociação', 'Profissional', 'english', 'supporting', 1, 3, 18, 'EN-15:3'],
];

const EVIDENCE: Row[] = [
  ['EV-01', 'GitHub', 'Público', 'evidence', 'core', 3, 4, 1],
  ['EV-02', 'Projetos pessoais', 'Projetos', 'evidence', 'core', 3, 4, 1],
  [
    'EV-03',
    'Documentação e decisões (README, ADR)',
    'Projetos',
    'evidence',
    'core',
    3,
    4,
    2,
  ],
  ['EV-04', 'Cases profissionais', 'Profissional', 'evidence', 'important', 2, 4, 4],
  ['EV-05', 'Artigos técnicos', 'Público', 'evidence', 'important', 2, 3, 6, 'EV-02:2'],
  ['EV-06', 'LinkedIn', 'Público', 'evidence', 'supporting', 2, 3, 6, 'EV-02:2'],
  ['EV-07', 'Open source', 'Comunidade', 'evidence', 'supporting', 1, 3, 10, 'SE-01:3'],
  ['EV-08', 'Apresentações', 'Comunidade', 'evidence', 'supporting', 1, 3, 12, 'EN-14:2'],
  [
    'EV-09',
    'Contribuições técnicas no trabalho',
    'Profissional',
    'evidence',
    'important',
    2,
    4,
    3,
  ],
  ['EV-10', 'Liderança técnica', 'Profissional', 'evidence', 'supporting', 1, 3, 15],
];

const INTERVIEW: Row[] = [
  ['IN-01', 'Python (entrevista)', 'Técnica', 'interview', 'core', 2, 4, 6, 'PY-03:2'],
  ['IN-02', 'SQL (entrevista)', 'Técnica', 'interview', 'core', 3, 4, 6, 'DB-03:2'],
  [
    'IN-03',
    'Coding / algoritmos',
    'Técnica',
    'interview',
    'important',
    2,
    3,
    6,
    'PY-07:2',
  ],
  ['IN-04', 'Debugging ao vivo', 'Técnica', 'interview', 'important', 2, 3, 8, 'PY-05:3'],
  ['IN-05', 'APIs e backend', 'Técnica', 'interview', 'important', 1, 3, 10, 'BE-03:3'],
  ['IN-06', 'Bancos de dados', 'Técnica', 'interview', 'important', 2, 4, 9, 'DB-05:3'],
  ['IN-07', 'Data Engineering', 'Técnica', 'interview', 'core', 1, 4, 11, 'DE-03:3'],
  [
    'IN-08',
    'Machine Learning',
    'Técnica',
    'interview',
    'supporting',
    0,
    3,
    16,
    'ML-04:2',
  ],
  ['IN-09', 'IA / LLM', 'Técnica', 'interview', 'important', 1, 3, 13, 'AI-05:3'],
  ['IN-10', 'System design', 'Técnica', 'interview', 'important', 0, 3, 13, 'SD-01:2'],
  ['IN-11', 'Behavioral (STAR)', 'Comportamental', 'interview', 'core', 2, 4, 9],
  [
    'IN-12',
    'Entrevista em inglês',
    'Comportamental',
    'interview',
    'core',
    2,
    4,
    9,
    'EN-09:2',
  ],
  ['IN-13', 'Take-home', 'Formato', 'interview', 'important', 1, 4, 12, 'SE-03:3'],
  ['IN-14', 'Live coding', 'Formato', 'interview', 'important', 1, 3, 12, 'IN-03:2'],
];

interface Revision {
  skillClass?: CareerSkillClass;
  target12?: number;
  target24?: number;
  prerequisites?: string;
}

/**
 * Consolidated revision (target profile: Senior Data / AI Engineer). Applied
 * on top of the original rows so nothing is removed and every change is
 * visible in one place. L4 at 24 months stays on the central competences
 * (Python, SQL, SE, backend, data engineering, AI engineering, databases,
 * AWS, system design); operational ones aim at L3; functional ones at L2–L3.
 */
const REVISIONS = new Map<string, Revision>([
  // Software Engineering / Backend — high depth
  ['SE-08', { skillClass: 'core', target12: 2, target24: 4 }],
  ['SE-05', { skillClass: 'core', target12: 3, target24: 4 }],
  ['SE-06', { target12: 3, target24: 3 }],
  ['BE-01', { skillClass: 'core', target12: 3, target24: 4 }],
  ['BE-02', { skillClass: 'core', target12: 3, target24: 4 }],
  ['BE-03', { skillClass: 'core', target12: 3, target24: 4 }],
  ['PY-08', { prerequisites: 'PY-03:3,PY-06:2' }],
  // Databases — SQL básico → intermediário → PostgreSQL → índices
  ['DB-01', { target12: 3, target24: 4 }],
  [
    'DB-05',
    {
      skillClass: 'important',
      target12: 3,
      target24: 3,
      prerequisites: 'DB-02:2,DB-04:1',
    },
  ],
  ['DB-06', { prerequisites: 'DB-05:2,DB-03:2' }],
  // Docker — operational (L3)
  ['DK-01', { target24: 3 }],
  ['DK-02', { target24: 3 }],
  ['DK-04', { target24: 3 }],
  ['DK-05', { target24: 3 }],
  // Data Engineering tools — functional
  ['DE-06', { skillClass: 'supporting', target12: 2, target24: 3 }],
  ['DE-07', { skillClass: 'supporting', target12: 2, target24: 3 }],
  // AWS — high depth
  ['CL-01', { skillClass: 'core', target12: 3, target24: 4 }],
  ['CL-02', { skillClass: 'core', target12: 3, target24: 4 }],
  ['CL-03', { skillClass: 'core', target12: 3, target24: 4 }],
  ['CL-04', { skillClass: 'core', target12: 3, target24: 4 }],
  ['CL-06', { skillClass: 'core', target12: 2, target24: 4 }],
  ['CL-09', { target12: 1, target24: 3 }],
  // MLOps — operational
  ['ML-06', { skillClass: 'important', target12: 1, target24: 3 }],
  // AI Engineering — RAG, evaluation and production are the deep part
  ['AI-01', { target24: 3 }],
  ['AI-02', { target24: 3 }],
  ['AI-03', { target24: 3 }],
  ['AI-04', { target24: 3 }],
  ['AI-05', { skillClass: 'core', target12: 3, target24: 4 }],
  ['AI-07', { skillClass: 'core', target12: 2, target24: 4 }],
  ['AI-08', { skillClass: 'core', target12: 1, target24: 4 }],
  ['AI-09', { prerequisites: 'AI-06:2,AI-07:2,AI-08:1' }],
  // Agents & chatbots — fundamentals operational, advanced functional
  ['AG-01', { target24: 3 }],
  ['AG-02', { target24: 2 }],
  ['AG-04', { skillClass: 'supporting', target24: 2 }],
  ['AG-06', { target24: 2 }],
  ['AG-07', { target12: 1, target24: 2 }],
  ['AG-10', { target24: 2 }],
  // Deep Learning / PyTorch — functional
  ['DL-01', { target24: 2 }],
  ['DL-02', { target12: 1, target24: 2 }],
  ['DL-03', { target24: 2 }],
  ['DL-04', { target24: 2 }],
  ['DL-05', { target24: 2 }],
  ['DL-07', { target24: 1 }],
  // System Design — high depth on the parts that matter for data/AI
  ['SD-01', { skillClass: 'core', target12: 1, target24: 4 }],
  ['SD-06', { skillClass: 'core', target12: 1, target24: 4 }],
  ['SD-02', { skillClass: 'important' }],
  ['SD-03', { skillClass: 'important' }],
  ['SD-04', { skillClass: 'important' }],
  ['SD-05', { skillClass: 'important' }],
  // BI — existing strength, kept functional
  ['BI-01', { target24: 3 }],
  ['BI-02', { target24: 3 }],
]);

/** Initial NOW/NEXT/LATER (the player can change it per skill). */
const HORIZONS = new Map<string, CareerHorizon>([
  ['PY-01', 'now'],
  ['PY-02', 'now'],
  ['SE-01', 'now'],
  ['LX-01', 'now'],
  ['LX-02', 'now'],
  ['PY-03', 'next'],
  ['DB-01', 'next'],
  ['DB-02', 'next'],
  ['DB-03', 'next'],
  ['DB-05', 'next'],
  ['BE-01', 'next'],
  ['BE-02', 'next'],
  ['SE-03', 'next'],
  ['DK-01', 'next'],
  ['DK-02', 'next'],
  ['DE-08', 'later'],
  ['DE-09', 'later'],
  ['CL-09', 'later'],
  ['DL-03', 'later'],
  ['DL-04', 'later'],
  ['DL-05', 'later'],
  ['DL-06', 'later'],
  ['DL-07', 'later'],
  ['AG-07', 'later'],
  ['DK-06', 'later'],
]);

const defaultHorizon = (
  attribute: CareerAttribute,
  startMonth: number,
): CareerHorizon => {
  // Technical NOW is reserved for the explicit list above; other attributes
  // run in parallel from day one (English is a daily habit).
  if (attribute !== 'technical' && startMonth <= 2) return 'now';
  return startMonth <= 6 ? 'next' : 'later';
};

const parsePrerequisites = (prereq: string): { id: string; level: number }[] =>
  prereq
    .split(',')
    .filter(Boolean)
    .map((item) => {
      const [skillId, level] = item.split(':');
      return { id: skillId, level: Number(level) };
    });

const toDefs = (attribute: CareerAttribute, rows: Row[]): CareerSkillDef[] =>
  rows.map(
    ([id, name, group, track, skillClass, target12, target24, startMonth, prereq]) => {
      const revision = REVISIONS.get(id) ?? {};
      return {
        id,
        attribute,
        group,
        name,
        skillClass: revision.skillClass ?? skillClass,
        target12: revision.target12 ?? target12,
        target24: revision.target24 ?? target24,
        startMonth,
        prerequisites: parsePrerequisites(revision.prerequisites ?? prereq ?? ''),
        criteria: CRITERIA[track],
        horizon: HORIZONS.get(id) ?? defaultHorizon(attribute, startMonth),
      };
    },
  );

export const CAREER_SKILLS: CareerSkillDef[] = [
  ...toDefs('technical', TECHNICAL),
  ...toDefs('english', ENGLISH),
  ...toDefs('evidence', EVIDENCE),
  ...toDefs('interview', INTERVIEW),
];

/** Criteria used by skills the player adds themselves, by attribute. */
export const CAREER_GENERIC_CRITERIA: Record<CareerAttribute, string[]> = {
  technical: CRITERIA['se'],
  english: CRITERIA['english'],
  evidence: CRITERIA['evidence'],
  interview: CRITERIA['interview'],
};

export const CAREER_ATTRIBUTES: { id: CareerAttribute; label: string; icon: string }[] = [
  { id: 'technical', label: 'Technical', icon: 'terminal' },
  { id: 'english', label: 'English', icon: 'translate' },
  { id: 'evidence', label: 'Professional Evidence', icon: 'workspace_premium' },
  { id: 'interview', label: 'Interview Readiness', icon: 'record_voice_over' },
];

export const CAREER_LEVEL_NAMES = [
  'Unknown',
  'Awareness',
  'Guided',
  'Autonomous',
  'Proficient',
  'Senior',
];

export const CAREER_CLASS_LABELS: Record<CareerSkillClass, string> = {
  core: 'CORE',
  important: 'IMPORTANT',
  supporting: 'SUPPORTING',
  awareness: 'AWARENESS',
};

export const CAREER_HORIZON_LABELS: Record<CareerHorizon, string> = {
  now: 'NOW',
  next: 'NEXT',
  later: 'LATER',
};
